# Generated by Django 4.1.7 on 2023-04-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_members', '0002_alter_card_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='author',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
