# Generated by Django 4.1.7 on 2023-03-12 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_members', '0002_category_members_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='cat',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_members.category'),
        ),
    ]
