# Generated by Django 4.1.7 on 2023-03-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_members', '0003_alter_members_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ['-time_created', 'title'], 'verbose_name': 'Members', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='members',
            name='title',
            field=models.CharField(max_length=100, verbose_name='login'),
        ),
    ]
